emp_id=input("Enter employee id:")
emp_name=input("Enter employee name:")
gender=input("Gender:")
salary=input("Annual salary:")
print("Employee ID: ",emp_id)
print("Employee Nmae:", emp_name)
print("Gender:", gender)
print("Annual salary:", salary)